### ISSUE TITLE
Xp will not go in the block...

### ISSUE THREAD

**Issue by therealeric** [bl4ckscor3/GlobalXP#23] opened 2020-11-13 18:44 UTC
I was using the Hero's Medallion from Reliquary to store my XP, until you were able to update your mod to 1.16.4.

I built the block and took a bunch of XP out of the Medallion and tried to put it in your  block.

I shift-Right Clicked, no good, I Right Clicked in case you changed to controls, no good...

I am using version 1.4.15
I am using Minecraft 1.16.4
I am using Forge 35.0.7

I'm sorry, I think I broke it.  Please help me fix it...

**Comment by bl4ckscor3** [comment] 2020-11-14 10:41
I can't reproduce this. I stored XP in the Hero's Medallion, put it back into my XP bar, then successfully stored all of that XP in the XP Block by sneak-rightclicking the block. Does it look like your player is crouching when you press shift? Do you have sneaking rebound to a different key?

**Comment by therealeric** [comment] 2020-11-14 11:12
I knew my problem was going to be unique...

Yes, I am crouching on Left Shift press.  As far as I know all my vanilla Minecraft key bindings are default.

It looks like it is time for a new world, to see if the problem is still there.

I'll keep you posted...

**Comment by therealeric** [comment] 2020-11-14 11:31
A newly generated world...

XP from bottles of Enchanting, 18 levels.

Exactly the same situation.  Hero's Medallion work perfectly.  Your mod, GlobalXP,  broken...

I used your mod in my "kitchen sink" 1.16.3 worlds and all was great.  I actually like your mod better than the Hero's Medallion...

I don't know where to go from here.

Let me if there is anything else you would like me to try...

This problem is likely going to be left as an Unknown...

Thanks for your time...

**Comment by bl4ckscor3** [comment] 2020-11-14 17:42
1. Remove half the mods that you have installed and set them aside - but keep Global XP installed.
2. Start the game.
3. If your issue persists, start again with step 1. If it does not persist, swap the mods you still have installed with the ones you most recently set aside - but keep Global XP installed. Go to step 2.

Do this until you have found a minimal set of mods with which the issue is reproducible. Please tell me your results.

**Comment by therealeric** [comment] 2020-11-14 19:50
This could take a little time.  I'll try it out.

Do I need to delete the mods or is it okay to disable them through the launcher?

**Comment by bl4ckscor3** [comment] 2020-11-14 22:05
Anything to make them not load into the game.

**Comment by therealeric** [comment] 2020-11-17 19:26
I tried to do what you instructed.  My Instance imploded...

Even putting everything back in, still no good...

It looks like that Instance was running on borrowed time even when it was running.

Sorry.

**Comment by bl4ckscor3** [comment] 2020-11-17 20:13
Don't worry. I'll close this for now. If you have more info or can reproduce this somehow in a way that I can easily do it as well, please comment again.

**Closed as completed by bl4ckscor3** 2020-11-17 20:13 UTC

**Comment by choekstr** [comment] 2020-11-28 03:07
Pack: TNP Limitless 3 version 1.8.0
Global XP version 1.4.15
Minecraft 1.16.4
Forge 35.1.4

I have the same exact issue as OP where I have 67 levels that won't go into the XP block despite everything I tried.  FWIW, I also can't get XP to go into the Cyclic XP Pylon and have left and issue on their github to investigate if possible.  The hero's medallion works perfectly to push and pull XP from the character.

There are 267 mods in this pack, so your thought of a mod conflict could absolutely be the case, but ugh, trying to track down which mod conflicts is not an easy task.

I tried a brand new fresh superflat world and gave myself some levels and it worked perfectly.  So it's either the XP received from FTP Quests (almost every bit of it was a mass quest accepting session) or it was something else in the world that is causing the problem.  

Just documenting this here in case others are hunting for a solution as well in the future.

**EDIT:  I just realized I didn't realize I had a shield equipped and it was causing the issue.  Removed the shield and it worked again.**

**Comment by bl4ckscor3** [comment] 2020-11-28 10:36
Thanks for your comment! So it is a problem with Global XP after all... I can't really fix this though, because vanilla does the decision whether or not to allow block activation with an item in your offhand while sneaking, and I have no control over that. The only way to fix it would mean mods like FTB Chunks can no longer properly restrict access to the XP Block which is also not desired.

**Comment by therealeric** [comment] 2020-12-05 22:18
Just a piece of slightly related information I noticed today, while looking at the FTB Chunks change log.  There appears that there might be a "interaction whitelist" that you could possibly have your block added to, to allow use.

I hope this might be useful to you.

Keep up the great work and stay healthy in your "plague bunker".

**Comment by bl4ckscor3** [comment] 2020-12-05 23:56
I took a poke in the code, and that tag completely bypasses the mode the chunk is set to, which may not be desirable in some cases (see [here](https://github.com/FTBTeam/FTB-Chunks/blob/b6256cfb2466c27dbfa65d0f48f91b9d77a52df8/src/main/java/com/feed_the_beast/mods/ftbchunks/impl/ClaimedChunkImpl.java#L90) for the relevant code line).
